name: Create Pylint badge

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies and clear old pylint.svg
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install anybadge
          rm pylint.svg
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import sys
            from pylint.lint import Run
            from anybadge import Badge
            from io import StringIO

            stdout = sys.stdout
            sys.stdout = StringIO()

            ARGS = ['ddpp.py', '--reports=n']
            Run(ARGS, exit=False)
            output = sys.stdout.getvalue()
            sys.stdout = stdout
            last_line = output.split('\n')[-3]
            print(last_line)
            score = last_line.split()[6].split('/')[0]
            thresholds = {2: 'red',
                          4: 'orange',
                          6: 'yellow',
                          10: 'green'}

            badge = Badge('pylint', score, thresholds=thresholds)
            badge.write_badge("pylint.svg")
      - name: Commit files
        id: commit
        run: |
            git config --local user.email "luc@nothome.xyz"
            git config --local user.name "pylint-badge"
            git add --all
              if [-z "$(git status --porcelain)"]; then
            echo "::set-output name=push::false"
            else
            git commit -m "update pylint.svg" -a
            echo "::set-output name=push::true"
            fi
        shell: bash
      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
